name: Old_Film
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.5.30=py36h5fab9bb_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - dill=0.3.4=pyhd8ed1ab_0
  - dlib=19.22.0=py36h446f8a6_0
  - easydict=1.9=py_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9d=h36c2ea0_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=11.2.0=h69a702a_14
  - libgfortran5=11.2.0=h5c6108e_14
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h27cfd23_0
  - llvmlite=0.36.0=py36h612dafd_4
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numba=0.53.1=py36ha9443f7_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1k=h7f98852_0
  - pillow=8.2.0=py36he98fc37_0
  - pip=21.1.2=py36h06a4308_0
  - python=3.6.13=h12debd9_1
  - python_abi=3.6=2_cp36m
  - pytorch=1.5.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tbb=2020.3=hfd86e86_0
  - tensorboardx=2.5=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.6.1=py36_cu101
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.13.0
    - addict==2.4.0
    - albumentations==1.0.0
    - beautifulsoup4==4.10.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==4.4.2
    - einops==0.3.0
    - filelock==3.3.1
    - flow-vis==0.1
    - flow-vis-torch==0.1
    - future==0.18.2
    - gdown==4.2.0
    - google-auth==1.32.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.1
    - guided-filter-pytorch==3.7.5
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==4.6.0
    - kiwisolver==1.3.1
    - lmdb==1.2.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - networkx==2.5.1
    - oauthlib==3.1.1
    - opencv-python==4.5.2.54
    - opencv-python-headless==4.5.2.54
    - pandas==1.1.5
    - protobuf==3.17.3
    - ptflops==0.6.8
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.17.2
    - scipy==1.5.4
    - seaborn==0.11.2
    - soupsieve==2.2.1
    - tb-nightly==2.6.0a20210626
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - thop==0.0.31-2005241907
    - tifffile==2020.9.3
    - timm==0.4.12
    - tqdm==4.61.1
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - yapf==0.31.0
    - you-get==0.4.1536
    - zipp==3.4.1
